### ISSUE TITLE
Invalid NPM module

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-foundation-modal#3]
I went ahead and tried to plugin 0.2.0 to a project, and it looks like maybe the index.js file isn't part of the npm distribution. Is this something you can fix on your end?

**Comment by williamsbdev** [comment]
@benkiefer @toranb I did an npm publish of 0.2.1 to fix this issue. It must have been a bad `npm publish` as it was not in the `.gitignore` or the `.npmignore` files.

**Comment by toranb** [comment]
wat? scumbag npm

thanks for the quick turnaround @williamsbdev !!!

**Comment by benkiefer** [comment]
Perfect. Thanks to both of you. Works great now.
