### ISSUE TITLE
Right after install: TypeError: $(...).foundation is not a function

### ISSUE THREAD

**Issue by ahouchens** [toranb/ember-cli-foundation-modal#5]
$(document).foundation({
      reveal: {
        root_element: modalRoot,
        animation_speed: animationSpeed
      }
    });

**Comment by toranb** [comment]
What does your Brocfile look like? Also - where did you use the code shown above?

**Comment by williamsbdev** [comment]
I'm going to close this issue since it has not been worked in nearly a year.
